### ISSUE TITLE
Current song unmutes if it ends in the middle of a playlist preview.

### ISSUE THREAD

**Issue by Erthkwake** [plugCubed/plugCubed#105]
When you doubleclick to preview a song in the playlist, the current song mutes so you can hear it undisturbed. But if the current song ends, it gets unmuted, even if you are still previewing.

This would be fixed if all songs were muted instead of just the current one when previewing.

**Comment by TheBanHammer** [comment]
@thedark1337 please confirm and assign a label to this bug. Issues site no longer works. Can not check resolution.
