### ISSUE TITLE
disable button

### ISSUE THREAD

**Issue by Ddawg747** [plugCubed/plugCubed#133]
you guys should add a disable button for people that dont want to run it anymore but dont want to refresh and lose their spot in the queue

**Comment by JTBrinkmann** [comment]
if you are not afraid of using the console, you can run
``plugCubed.close()``
to close plug³. It doesn't close plug³ 100% (e.g. the volume button and enlarge button are not completly reset), but it's at least something

**Comment by thedark1337** [comment]
You only lose your spot in waitlist if the refreshing takes more than a certain amount of time. Something like more than 5 minutes or so.
