### ISSUE TITLE
JSON Code to Remove Video Frame

### ISSUE THREAD

**Issue by ROBOTunderscore** [plugCubed/plugCubed#134]
I used a JSON script to give my room a custom background whenever a user runs plugCubed in it: https://api.myjson.com/bins/50d1t

Thing is, it leaves this annoying underwater-themed video frame with everything else: http://i.imgur.com/wbvrVw5.png

What line of code should I add to my JSON script so the video frame is removed when a user runs plugCubed in my room? 

(I created the script with minimal knowledge from a reddit post. My issue is that I can't find the full list of modifiable objects/assets I can use in my JSON script; I only know that "background" lets me change the background.)

**Comment by goto-bus-stop** [comment]
The playback background is a `<div>` with class `.background`, and contains an `<img />` element.

One simple way to completely remove it is by setting its "display" property to "none", like so:

```json
{
  "#playback .background": { "display": "none" }
}
```

**Comment by JTBrinkmann** [comment]
That frame is also called "playback border", and you can set a custom one by adding
``, playback: "http://…"`` after your background url (still within the ``"images": {…}``), where you can replace http://… with whatever image you want to replace it with. If you really want to completly remove it, you can use goto-bus-stop's suggestion, which however you'd need to put into css.rule, so your complete room settings (.json) file should look like
```
{
	"images": {
		"background": "https://i.imgur.com/fryXCKD.png"
	},
	"css": {
		"rule": {
			"#playback .background": { "display": "none" }
		}
	}
}
```
to actually work

**Comment by ROBOTunderscore** [comment]
Yeah, it didn't work before adding the "css" rule.

But it works now!
Thanks to both of you for helping me out!
