### ISSUE TITLE
Room settings - Room's custom CSS persists

### ISSUE THREAD

**Issue by Strat-** [plugCubed/plugCubed#135]
On loading a room (using the plug3 loader userscript, Google Chrome), plug3 loads the room's custom CSS.

I want to disable it, but when I go to plug3's settings, Room Settings is already unchecked. If I check and then uncheck it, the custom style doesn't get unloaded.

*update* Even if it is set to "on" on room join (different room), it still doesn't unload the custom style.

**Comment by thedark1337** [comment]
Please try the latest build and let me know if that works.

**Comment by Strat-** [comment]
Works fine now.
