### ISSUE TITLE
Previous messages cycling broken for links and emotes

### ISSUE THREAD

**Issue by ProditorMagnus** [plugCubed/plugCubed#137]
Plugcubed has undocumented feature of cycling previous messages, however it is somewhat broken. Instead of showing original message it returns html markup of message elements, like `<a href="https://plug.dj" target="_blank">https://plug.dj</a>`

**Comment by thedark1337** [comment]
I'll see if i can somehow enhance this feature to not save HTML.

**Comment by thedark1337** [comment]
Fixed in https://github.com/plugCubed/plugCubed/commit/5bae407fa6bdcd24adafc5e6d1f9580f8d78e125
