### ISSUE TITLE
PlugCubed is only running Lite?

### ISSUE THREAD

**Issue by Kh1326** [plugCubed/plugCubed#138]
I'm using the regular PlugCubed but when I click the bookmark on PlugDJ, I get this in the chat "Running plug³ in Lite!
Some features will not work."

**Comment by JTBrinkmann** [comment]
plug³ code needs to be updated on each plug.dj update. After the last plug.dj update, plug³ hasn't been updated yet, so some features are not available (in other words, you are running plug³ Lite).
There is nothing YOU can do about it, except for waiting for the plug³ update.

**Comment by JTBrinkmann** [comment]
To clear that up, plug³ and plug³ Lite are the NOT different versions of the script. The "Lite" just means, that it's not optimized for the current plug.dj version.

**Comment by thedark1337** [comment]
I have updated to the latest plug.dj version and made a few features work both in Lite and Normal mode. 

The only difference between Lite and Normal is that in Lite some features will not work. They are not different scripts.
