### ISSUE TITLE
Room Settings fails to load

### ISSUE THREAD

**Issue by anjanms** [plugCubed/plugCubed#140]
Getting the room description fails with this error at plugCubed/RoomSettings line 177.
```
Uncaught TypeError: Cannot read property 'get' of undefined
```

Upon further investigation it appears plug has removed 'fx' from the room model, so this call to ModuleLoader returns undefined.
```
RoomModel = ModuleLoader.getView({
    isBackbone: true,
    isModel: true
});
```
(plugCubed/RoomSettings line 36)

**Comment by thedark1337** [comment]
Thank you for the bug report, i'll look into fixing it
