### ISSUE TITLE
Typo in "/commands"

### ISSUE THREAD

**Issue by greenbigfrog** [plugCubed/plugCubed#141]
Hi!

I know you've stopped development.
But since they are back I thought I might just write it here anyway:
in `/commands` it's saying `/badges onoff` instead of `/badges on/off`

Thanks for your great work!

**Comment by thedark1337** [comment]
As plug has come back development has resumed. I'll work on fixing the typos as they are reported in :+1:

**Comment by thedark1337** [comment]
Fixed in https://github.com/plugCubed/plugCubed/commit/ff8c215ed95a8f853eb599e8152563a3acee33b6

Thanks
