### ISSUE TITLE
Background Image issue in JSON when using RSS Hosting

### ISSUE THREAD

**Issue by gitwaverr** [plugCubed/plugCubed#151]
I've been trying to use your plugCubed RSS Hosting feature to store my room settings. I've been trying to set up a background image, but when I save the file using the string "https://example.com/example.jpg" it saves the value with no "\\" as described in the examples on your website. However, if i try to add the "\\" character myself so that i get something like "https:\\/\\/example.com\\/example.jpg", it seems to save the result as "https:\\\\/\\\\/example.com\\\\/example.jpg" when i go back and look at the file by clicking on the link provided with the @p3="foo" result. 

I don't seem to be getting the image to show up in either case. Am I doing something wrong here? 

Apologies if this is the wrong place to post. I couldnt find anything else on the site links.

**Comment by thedark1337** [comment]
the \/ syntax is just for escaping JSON (which in this case is not 100% necessary)

As for the background image, are you setting it with your own URL or are you trying to use that example (which is just an example, not meant to actually be used). May I see what your room settings look like ?

**Comment by gitwaverr** [comment]
Sure. My room settings are very basic (your template) with just the room image change. I've been trying to use a web location ...

https://rss.plugcubed.net/get/58cb1673b5264

{"author":"","colors":{"background":"","chat":{"admin":"","ambassador":"","host":"","cohost":"","manager":"","bouncer":"","residentdj":""},"footer":"","header":""},"css":{"font":[],"import":[],"rule":[]},"images":{"background":"https://t3.ftcdn.net/jpg/01/35/31/76/500_F_135317630_1BGgf4XEUi2pCBM9n726D6QqC9aEEv05.jpg","booth":"","icons":{"admin":"","ambassador":"","host":"","cohost":"","manager":"","bouncer":"","residentdj":""},"playback":""},"rules":{"allowAutojoin":"true","allowAutorespond":"true","allowAutowoot":"true","allowEmotes":"true","allowShowingMehs":"true"}}

**Comment by MikeyWazowsky** [comment]
🤔 your room settings works for me

**Comment by gitwaverr** [comment]
Ugh! I logged out and back in and now it shows. Well I'm a moron. Sorry to bother you on this. :( Though while i have you here, is there any way to edit the saved room settings without having to create a new link?

**Comment by MikeyWazowsky** [comment]
@gitwaverr it's not possible if you host it on https://rss.plugcubed.net/

**Comment by gitwaverr** [comment]
ok thanks. Again, sorry to bother you on this. Please close this as major "user error". Thanks for the quick response though.

**Comment by thedark1337** [comment]
For further info, plugCubed doesn't currently update room settings when you change the room description so you can either reload plugCubed or refresh the webpage and it'll work. I'll try and get that up and working for a future release though 👍
