### ISSUE TITLE
No autowoot

### ISSUE THREAD

**Issue by VinylPhil** [plugCubed/plugCubed#154]
My Plug cubed stopped autowooting for some reason and I don't know why. It used to work, but now it doesn't.

**Comment by dh111** [comment]
@VinylPhil Are you using extension or bookmark version of plugCubed. If you are using the extension version we are aware we seem to have some issues with it right now.

**Comment by thedark1337** [comment]
Hi there,

1) Is the room you're in using any room settings? If so, can you see if they have "`allowAutowoot": "false"` set?
2) Can you check in the p3 menu if the auto woot option is enabled?
3) Which version are you running that you are having issues with? (You can either view it in the menu, the message in chat when its first loaded, or the /version command)
4) The auto woot functionality has a random delay from 1 to 10 seconds, this is to prevent spamming plug.dj's server.

**Comment by VinylPhil** [comment]
The autowoot function doesn't appear at all. The room uses p3 because other staff members use it too. I pulled it directly from the download https://plugcubed.net/ and the Firefox Browser extension 4.4.0-release (Build 6).

**Comment by thedark1337** [comment]
@VinylPhil if it doesn't appear in the menu that means that the room settings has it disabled, which room is having this issue?

**Comment by VinylPhil** [comment]
https://plug.dj/mineheroes

**Comment by thedark1337** [comment]
Issue resolved. User wasn't able to see option til I pointed it out 👍
