### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by wowweemip-fan** [plugCubed/plugCubed#166]
How do I remove it? 
[I removed the extension, and it's still there]

**Comment by Isebella** [comment]
We're sad to see you go, what browser are you using?

**Comment by wowweemip-fan** [comment]
Google Chrome

**Comment by Isebella** [comment]
@wowweemip-fan chrome://extensions/ go there try removing it from the source its self, also try looking in your bookmkars bar.

**Comment by wowweemip-fan** [comment]
@Isebella It's still popping up on plugdj even though I removed the bookmarklet and extension....

**Comment by Isebella** [comment]
@wowweemip-fan Have you cleared your cache and restarted your chrome since you removed the plugin?

**Comment by wowweemip-fan** [comment]
@Isebella That's exactly what I forgot to do. Thank you Isebella, you are a lifesaver.

**Comment by Isebella** [comment]
@wowweemip-fan No Problem 👍
